import Head from 'next/head';
import { FC, ReactNode } from 'react';
import { MainFooter, NavHeader } from '../organisms';

type Props = {
  children: ReactNode;
  lang?: string;
  title?: string;
  description?: string;
};

export const MainLayout: FC<Props> = ({
  children,
  lang = 'en',
  title = 'Next App !',
  description = 'Generated by create next app',
}) => {
  return (
    <div className='min-h-screen flex justify-between flex-col w-full font-roboto bg-blue_bg text-slate-400 text-sm'>
      <NavHeader />
      <div className='h-full w-full mt-6 px-3'>
        <Head>
          {/* <html lang={lang}></html> */}
          <title>{title}</title>
          <meta name='description' content={description} />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {children}
      </div>
      <MainFooter />
    </div>
  );
};
